services:
  - type: web
    name: stockage-cloud-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: QUOTA_PAR_UTILISATEUR
        value: "2199023255552"
      - key: TAILLE_MAX_FICHIER
        value: "5368709120"
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        value: fichiers
      - key: ORIGINE_AUTORISEE
        value: "*"
